package org.metaquill.pos

class POSTag private (val name:String, val isVerb:Boolean, val isNoun:Boolean, val isAdjective:Boolean) {
  this(name:String) = this(name, false, false, false)
}

object POSTag {
  val Tick = new POSTag("``")
  val Dash = new POSTag("--")
  val Comma = new POSTag(",")
  val Colon = new POSTag(":")
  val Period = new POSTag(".")
  val Quote = new POSTag("''")
  val DblQuote = new POSTag("\"")
  val LParen = new POSTag("(")
  val RParen = new POSTag(")")
  val CC = new POSTag("CC")
  val CD = new POSTag("CD")
  val DT = new POSTag("DT")
  val EX = new POS("EX")
  val FW = new POS("FW")
  val IN = new POS("IN")
  val JJ = new POS("JJ", false, false, true)
  val JJR = new POS("JJR", false, false, true)
  val JJS = new POS("JJS", false, false, true)
  val JJSS = new POS("JJSS", false, false, true)
  val LS = new POS("LS")
  val MD = new POS("MD")
  val NN = new POS("NN", false, true, false)
  val NNP = new POS("NNP", false, true, false)
  val NNPS = new POS("NNPS", false, true, false)
  val NNS = new POS("NNS", false, true, false)
  val NP = new POS("NP", false, true, false)
  val NPS = new POS("NPS", false, true, false)
  val PDT = new POS("PDT")
  val POS = new POS("POS")
  val PP = new POS("PP")
  val PRP = new POS("PRP")
  val PRP$ = new POS("PRP$")
  val PRP$R = new POS("PRP$R")
  val RB = new POS("RB")
  val RBR = new POS("RBR")
  val RBS = new POS("RBS")
  val RP = new POS("RP")
  val SYM = new POS("SYM")
  val TO = new POS("TO")
  val UH = new POS("UH")
  val VB = new POS("VB")
  val VBD = new POS("VBD")
  val VBG = new POS("VBG")
  val VBN = new POS("VBN")
  val VBP = new POS("VBP")
  val VBZ = new POS("VBZ")
  val WDT = new POS("WDT")
  val WP = new POS("WP")
  val WP$ = new POS("WP$")
  val WRB = new POS("WRB")
}
